[package]
name = "pulumi_gestalt_providers_azure_mini"
version.workspace = true
edition.workspace = true

[dependencies]
wit-bindgen.workspace = true
pulumi_gestalt_rust.workspace = true
bon.workspace = true
serde.workspace = true

[build-dependencies]
pulumi_gestalt_build.workspace = true