[package]
name = "changelog_lib"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
gix.workspace = true
tempfile.workspace = true
serde.workspace = true
bon.workspace = true
serde_yaml.workspace = true
regex.workspace = true
once_cell.workspace = true