[package]
name = "pulumi_gestalt_adapter_wasm_runner"
version.workspace = true
edition.workspace = true
repository.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prost.workspace = true
log.workspace = true
wasmtime.workspace = true
wasmtime-wasi.workspace = true
anyhow.workspace = true
tokio.workspace = true
log4rs.workspace = true
clap.workspace = true
pulumi_gestalt_core_proto = { workspace = true, features = ["connectivity"] }
pulumi_gestalt_adapter_wasm_wit = { workspace = true, features = ["runner"] }
pulumi_gestalt_adapter_wasm_component_creator.workspace = true
wasmparser.workspace = true
serde.workspace = true
serde_json.workspace = true
pulumi_gestalt_core_grpc.workspace = true

[dev-dependencies]
wat.workspace = true